package busstation;

import static busstation.LogIn.*;
import java.sql.*;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ManageClients extends javax.swing.JFrame {

    boolean View1 = false, View2 = false;

    public ManageClients() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        StartConnection();
        ReadDataBase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameTextField = new javax.swing.JTextField();
        AddressTextField = new javax.swing.JTextField();
        LastNameTextField = new javax.swing.JTextField();
        PhoneNumberTextField = new javax.swing.JTextField();
        BirthDateTextField = new javax.swing.JTextField();
        ViewButton2 = new javax.swing.JToggleButton();
        ViewButton1 = new javax.swing.JToggleButton();
        ExitButton = new javax.swing.JButton();
        ModifyButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        GenderComboBox = new javax.swing.JComboBox<>();
        TypeComboBox = new javax.swing.JComboBox<>();
        PasswordField2 = new javax.swing.JPasswordField();
        PasswordField1 = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ClientsTable = new javax.swing.JTable();
        NameLabel = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        AddressLabel = new javax.swing.JLabel();
        GenderLabel = new javax.swing.JLabel();
        PhoneLabel = new javax.swing.JLabel();
        BirthDateLabel = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        TittleLabel = new javax.swing.JLabel();
        PasswordLabel2 = new javax.swing.JLabel();
        TypeLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("BusStation Pátzcuaro: Admin de clientes");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameTextField.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        NameTextField.setToolTipText("Escribe aquí el nombre de pila del usuario.");
        NameTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 1, true));
        getContentPane().add(NameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 200, 30));

        AddressTextField.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        AddressTextField.setToolTipText("Proporciona una dirección o ubicación del usuario.");
        AddressTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 1, true));
        getContentPane().add(AddressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 200, 30));

        LastNameTextField.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        LastNameTextField.setToolTipText("Escribe aquí el o los apellidos del usuario.");
        LastNameTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 1, true));
        getContentPane().add(LastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 200, 30));

        PhoneNumberTextField.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        PhoneNumberTextField.setToolTipText("Proporciona un número de teléfono del usuario.");
        PhoneNumberTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 1, true));
        getContentPane().add(PhoneNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 200, 30));

        BirthDateTextField.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        BirthDateTextField.setToolTipText("Escribe la fecha de nacimiento con el formato que se indica.");
        BirthDateTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 1, true));
        getContentPane().add(BirthDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 200, 30));

        ViewButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/view.png"))); // NOI18N
        ViewButton2.setToolTipText("Clíck aqui para mostrar tu contraseña legible.");
        ViewButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(ViewButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 30, 30));

        ViewButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/view.png"))); // NOI18N
        ViewButton1.setToolTipText("Clíck aqui para mostrar tu contraseña legible.");
        ViewButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(ViewButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 30, 30));

        ExitButton.setBackground(new java.awt.Color(255, 153, 153));
        ExitButton.setText("CERRAR");
        ExitButton.setToolTipText("Click aquí para cerrar la ventana.");
        ExitButton.setBorder(null);
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 60, 20));

        ModifyButton.setBackground(new java.awt.Color(102, 153, 255));
        ModifyButton.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        ModifyButton.setText("MODIFICAR");
        ModifyButton.setToolTipText("Click aquí para modificar el cliente seleccionado.");
        ModifyButton.setBorder(null);
        ModifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ModifyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 170, 30));

        DeleteButton.setBackground(new java.awt.Color(255, 153, 153));
        DeleteButton.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        DeleteButton.setText("ELIMINAR");
        DeleteButton.setToolTipText("Click aquí para eliminar el cliente seleccionado.");
        DeleteButton.setBorder(null);
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 170, 30));

        AddButton.setBackground(new java.awt.Color(153, 255, 153));
        AddButton.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        AddButton.setText("AGREGAR");
        AddButton.setToolTipText("Click aquí para agregar un nuevo cliente con los datos proporcionados.");
        AddButton.setBorder(null);
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 170, 30));

        GenderComboBox.setBackground(new java.awt.Color(102, 153, 255));
        GenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        GenderComboBox.setToolTipText("Selecciona aquí el sexo del usuario.");
        getContentPane().add(GenderComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 200, -1));

        TypeComboBox.setBackground(new java.awt.Color(102, 153, 255));
        TypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "CLIENT" }));
        TypeComboBox.setToolTipText("Selecciona aquí el rango del usuario.");
        getContentPane().add(TypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 200, -1));

        PasswordField2.setToolTipText("Confirma aquí la contraseña.");
        getContentPane().add(PasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 170, 30));

        PasswordField1.setToolTipText("Escribe aquí la contraseña.");
        getContentPane().add(PasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 170, 30));

        ClientsTable.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        ClientsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Telefono", "Direccion", "Sexo", "Fecha Nacimiento", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ClientsTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 660, 170));

        NameLabel.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        NameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameLabel.setText("Nombre:");
        getContentPane().add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 200, 30));

        LastNameLabel.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        LastNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LastNameLabel.setText("Apellidos:");
        getContentPane().add(LastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 200, 30));

        AddressLabel.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        AddressLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddressLabel.setText("Direccion:");
        getContentPane().add(AddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 200, 30));

        GenderLabel.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        GenderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GenderLabel.setText("Sexo:");
        getContentPane().add(GenderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 200, 30));

        PhoneLabel.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        PhoneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PhoneLabel.setText("Teléfono:");
        getContentPane().add(PhoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 200, 30));

        BirthDateLabel.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        BirthDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BirthDateLabel.setText("Fecha de Nacimiento (dd/mm/aa):");
        getContentPane().add(BirthDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 200, 30));

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo480.jpg"))); // NOI18N
        Logo.setToolTipText("");
        Logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 680, 40));

        TittleLabel.setFont(new java.awt.Font("HelvLight", 1, 14)); // NOI18N
        TittleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TittleLabel.setText("Registro y administracion de Usuarios");
        getContentPane().add(TittleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 680, 30));

        PasswordLabel2.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        PasswordLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordLabel2.setText("Confirmar contraseña:");
        getContentPane().add(PasswordLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 200, 30));

        TypeLabel.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        TypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TypeLabel.setText("Tipo de usuario:");
        getContentPane().add(TypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 200, 30));

        PasswordLabel.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        PasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordLabel.setText("Contraseña:");
        getContentPane().add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 200, 30));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WhiteSolidBackground.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ReadDataBase() {
        int i = 0;
        int rn = ClientsTable.getRowCount();
        DefaultTableModel table = (DefaultTableModel) ClientsTable.getModel();
        while (i < rn) {
            table.removeRow(0);
            i++;
        }
        try {
            Statement st;
            st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM client;");
            while (rs.next()) {
                String Row[] = new String[]{rs.getString("IdClient"), rs.getString("Name") + " " + rs.getString("LastName"),
                    rs.getString("PhoneNumber"), rs.getString("Address"), rs.getString("Gender"), rs.getString("BirthDate"), "Cliente"};
                table.addRow(Row);
            }
        } catch (SQLException ex) {
        }
        try {
            Statement st;
            st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM admin;");
            while (rs.next()) {
                String Row[] = new String[]{rs.getString("IdAdmin"), rs.getString("Name") + " " + rs.getString("LastName"),
                    rs.getString("PhoneNumber"), rs.getString("Address"), rs.getString("Gender"), rs.getString("BirthDate"), "Administrador"};
                table.addRow(Row);
            }
        } catch (SQLException ex) {
        }
    }

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        this.dispose();
        MasterMenu.A = false;
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void ModifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyButtonActionPerformed
        int i = ClientsTable.getSelectedRow();
        if (i == -1)
            JOptionPane.showMessageDialog(null, "No has seleccionado nada", "Error", JOptionPane.ERROR_MESSAGE);
        else {
            try {
                int id = Integer.parseInt(ClientsTable.getValueAt(i, 0).toString());
                Statement st;
                st = con.createStatement();
                if (String.valueOf(ClientsTable.getValueAt(i, 6)).substring(0, 1).equalsIgnoreCase("C")) {
                    st.executeUpdate("UPDATE client SET Name='" + NameTextField.getText() + "', LastName='"
                            + LastNameTextField.getText() + "', PhoneNumber=" + PhoneNumberTextField.getText() + ", Address='"
                            + AddressTextField.getText() + "', Gender='" + GenderComboBox.getSelectedItem().toString().substring(0, 1) + "', BirthDate='"
                            + BirthDateTextField.getText() + "' WHERE IdClient=" + id);
                } else {
                    st.executeUpdate("UPDATE admin SET Name='" + NameTextField.getText() + "', LastName='"
                            + LastNameTextField.getText() + "', PhoneNumber=" + PhoneNumberTextField.getText() + ", Address='"
                            + AddressTextField.getText() + "', Gender='" + GenderComboBox.getSelectedItem().toString().substring(0, 1) + "', BirthDate='"
                            + BirthDateTextField.getText() + "' WHERE IdAdmin=" + id);
                }

                ReadDataBase();
                JOptionPane.showMessageDialog(null, "Se Actualizaron los datos del cliente", "Listo", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
            }
        }
    }//GEN-LAST:event_ModifyButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        int i = ClientsTable.getSelectedRow();
        if (i == -1)
            JOptionPane.showMessageDialog(null, "No has seleccionado nada.", "Error", JOptionPane.ERROR_MESSAGE);
        else {
            try {
                int id = Integer.parseInt(ClientsTable.getValueAt(i, 0).toString());
                Statement st;
                st = con.createStatement();
                if (String.valueOf(ClientsTable.getValueAt(i, 6)).substring(0, 1).equalsIgnoreCase("c")) {
                    st.executeUpdate("DELETE FROM client WHERE (IdClient='" + id +"');");
                } else if (String.valueOf(ClientsTable.getValueAt(i, 6)).substring(0, 1).equalsIgnoreCase("A")) {
                    st.executeUpdate("DELETE FROM admin WHERE (IdAdmin='" + id +"');");
                }
                DefaultTableModel table = (DefaultTableModel) ClientsTable.getModel();
                table.removeRow(i);
                JOptionPane.showMessageDialog(null, "Se elimino el usuario", "Listo", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
            }
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        try {

            boolean exists = false;
            String comp = "";
            String user = NameTextField.getText() + " " + LastNameTextField.getText();
            user = user.toLowerCase();

            Statement stF = con.createStatement();
            ResultSet rsF = stF.executeQuery("SELECT * FROM admin");

            while (rsF.next()) {
                String A = rsF.getString("Name");
                String B = rsF.getString("LastName");
                comp = A + " " + B;
                comp = comp.toLowerCase();
                if (comp.equalsIgnoreCase(user)) {
                    exists = true;
                }
            }
            stF.close();

            Statement stG = con.createStatement();
            ResultSet rsG = stG.executeQuery("SELECT * FROM client");

            while (rsG.next()) {
                String A = rsG.getString("Name");
                String B = rsG.getString("LastName");
                comp = A + " " + B;
                comp = comp.toLowerCase();
                if (comp.equalsIgnoreCase(user)) {
                    exists = true;
                }
            }
            stG.close();

            Statement st = con.createStatement();
            if ("".equals(NameTextField.getText()) || "".equals(LastNameTextField.getText()) || "".equals(BirthDateTextField.getText())
                    || "".equals(AddressTextField.getText()) || "".equals(PhoneNumberTextField.getText()) || "".equals(String.valueOf(PasswordField1.getPassword()))) {
                JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (exists == true) {
                JOptionPane.showMessageDialog(null, "Nombre ya existente en el sistema!", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (!Arrays.equals(PasswordField1.getPassword(), PasswordField2.getPassword())) {
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                if (TypeComboBox.getSelectedItem().toString().equalsIgnoreCase("Cliente")) {
                    st.execute("INSERT INTO `client` (`IdClient`,"
                            + " `Name`, `LastName`, `PhoneNumber`, `Address`, `Gender`, `BirthDate`, `Password`)"
                            + "VALUES (NULL,'"
                            + NameTextField.getText() + "','"
                            + LastNameTextField.getText() + "',"
                            + PhoneNumberTextField.getText() + ",'"
                            + AddressTextField.getText() + "','"
                            + String.valueOf(GenderComboBox.getSelectedItem()).substring(0, 1) + "','"
                            + BirthDateTextField.getText() + "','"
                            + String.valueOf(PasswordField1.getPassword()) + "');");
                } else {
                    st.execute("INSERT INTO `admin` (`IdAdmin`, "
                            + " `Name`, `LastName`, `PhoneNumber`, `Address`, `Gender`, `BirthDate`, `Password`)"
                            + "VALUES (NULL,'"
                            + NameTextField.getText() + "','"
                            + LastNameTextField.getText() + "','"
                            + PhoneNumberTextField.getText() + "','"
                            + AddressTextField.getText() + "','"
                            + GenderComboBox.getSelectedItem().toString().substring(0, 1) + "','"
                            + BirthDateTextField.getText() + "','"
                            + String.valueOf(PasswordField1.getPassword()) + "');");
                }
                JOptionPane.showMessageDialog(null, "El usuario ha sido agregado a la lista", "Listo", JOptionPane.INFORMATION_MESSAGE);
                ReadDataBase();
            }
        } catch (SQLException ex) {
            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    private void ViewButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewButton1ActionPerformed
        if (View1 == false) {
            PasswordField1.setEchoChar((char) 0);
            View1 = true;
        } else if (View1 == true) {
            PasswordField1.setEchoChar((char) '•');
            View1 = false;
        }
    }//GEN-LAST:event_ViewButton1ActionPerformed

    private void ViewButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewButton2ActionPerformed
        if (View2 == false) {
            PasswordField2.setEchoChar((char) 0);
            View2 = true;
        } else if (View2 == true) {
            PasswordField2.setEchoChar((char) '•');
            View2 = false;
        }
    }//GEN-LAST:event_ViewButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageClients().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JTextField AddressTextField;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel BirthDateLabel;
    private javax.swing.JTextField BirthDateTextField;
    private javax.swing.JTable ClientsTable;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JComboBox<String> GenderComboBox;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton ModifyButton;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JPasswordField PasswordField1;
    private javax.swing.JPasswordField PasswordField2;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel PasswordLabel2;
    private javax.swing.JLabel PhoneLabel;
    private javax.swing.JTextField PhoneNumberTextField;
    private javax.swing.JLabel TittleLabel;
    private javax.swing.JComboBox<String> TypeComboBox;
    private javax.swing.JLabel TypeLabel;
    private javax.swing.JToggleButton ViewButton1;
    private javax.swing.JToggleButton ViewButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
