package busstation;

import static busstation.LogIn.*;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ManageBuses extends javax.swing.JFrame {

    public ManageBuses() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        StartConnection();
        ReadDataBase();

        try {
            Statement st;
            st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT IdModel,Name FROM model;");
            while (rs.next()) {
                ModelComboBox.addItem(rs.getString("IdModel") + "-" + rs.getString("Name"));
            }
            ResultSet rs2 = st.executeQuery("SELECT IdDriver,Name FROM driver;");
            while (rs2.next()) {
                DriverComboBox.addItem(rs2.getString("IdDriver") + "-" + rs2.getString("Name"));
            }
            ResultSet rs3 = st.executeQuery("SELECT IdCompany,Name FROM company;");
            while (rs3.next()) {
                PropertyComboBox.addItem(rs3.getString("IdCompany") + "-" + rs3.getString("Name"));
            }
        } catch (SQLException ex) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EnrollmentTextField = new javax.swing.JTextField();
        PurchaseDateTextField = new javax.swing.JTextField();
        DriverComboBox = new javax.swing.JComboBox<>();
        PropertyComboBox = new javax.swing.JComboBox<>();
        ModelComboBox = new javax.swing.JComboBox<>();
        ExitButton = new javax.swing.JButton();
        ModifyButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        BusesTable = new javax.swing.JTable();
        ModelLabel = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        TittleLabel = new javax.swing.JLabel();
        DriverLabel = new javax.swing.JLabel();
        PropertyLabel = new javax.swing.JLabel();
        EnrollmentLabel = new javax.swing.JLabel();
        PurchaseDateLabel = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("BusStation Pátzcuaro: Admin de autobuses");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EnrollmentTextField.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        EnrollmentTextField.setToolTipText("Escribe aquí la matricula del bus.");
        EnrollmentTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 1, true));
        getContentPane().add(EnrollmentTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 200, 30));

        PurchaseDateTextField.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        PurchaseDateTextField.setToolTipText("Escribe aquí la fecha de adquisición del bus.");
        PurchaseDateTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 1, true));
        getContentPane().add(PurchaseDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 200, 30));

        DriverComboBox.setBackground(new java.awt.Color(153, 255, 255));
        DriverComboBox.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        DriverComboBox.setToolTipText("Selecciona aquí de entre los conductores disponibles.");
        DriverComboBox.setBorder(null);
        getContentPane().add(DriverComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 160, 30));

        PropertyComboBox.setBackground(new java.awt.Color(153, 255, 255));
        PropertyComboBox.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        PropertyComboBox.setToolTipText("Selecciona aquí de entre los propietarios disponibles.");
        PropertyComboBox.setBorder(null);
        getContentPane().add(PropertyComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 160, 30));

        ModelComboBox.setBackground(new java.awt.Color(153, 255, 255));
        ModelComboBox.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        ModelComboBox.setToolTipText("Selecciona aquí de entre los modelos disponibles.");
        ModelComboBox.setBorder(null);
        getContentPane().add(ModelComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 150, 30));

        ExitButton.setBackground(new java.awt.Color(255, 153, 153));
        ExitButton.setText("CERRAR");
        ExitButton.setToolTipText("Click aquí para cerrar la ventana.");
        ExitButton.setBorder(null);
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 60, 20));

        ModifyButton.setBackground(new java.awt.Color(102, 153, 255));
        ModifyButton.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        ModifyButton.setText("MODIFICAR");
        ModifyButton.setToolTipText("Click aquí para modificar el bus seleccionado.");
        ModifyButton.setBorder(null);
        ModifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ModifyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 170, 30));

        DeleteButton.setBackground(new java.awt.Color(255, 153, 153));
        DeleteButton.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        DeleteButton.setText("ELIMINAR");
        DeleteButton.setToolTipText("Click aquí para eliminar el bus seleccionado.");
        DeleteButton.setBorder(null);
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 170, 30));

        AddButton.setBackground(new java.awt.Color(153, 255, 153));
        AddButton.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        AddButton.setText("AGREGAR");
        AddButton.setToolTipText("Click aquí para agregar un nuevo bus con los datos proporcionados.");
        AddButton.setBorder(null);
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 170, 30));

        BusesTable.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        BusesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Modelo", "Matricula", "Fecha de Compra", "Conductor", "Propietario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(BusesTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 660, 170));

        ModelLabel.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        ModelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ModelLabel.setText("Modelo:");
        getContentPane().add(ModelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 150, 30));

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo480.jpg"))); // NOI18N
        Logo.setToolTipText("");
        Logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 680, 40));

        TittleLabel.setFont(new java.awt.Font("HelvLight", 1, 14)); // NOI18N
        TittleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TittleLabel.setText("Registro y administracion de Autobuses");
        getContentPane().add(TittleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 680, 30));

        DriverLabel.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        DriverLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DriverLabel.setText("Conductor:");
        getContentPane().add(DriverLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 80, 30));

        PropertyLabel.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        PropertyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PropertyLabel.setText("Propietario:");
        getContentPane().add(PropertyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 80, 30));

        EnrollmentLabel.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        EnrollmentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EnrollmentLabel.setText("Matricula:");
        getContentPane().add(EnrollmentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 200, 30));

        PurchaseDateLabel.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        PurchaseDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PurchaseDateLabel.setText("Fecha de compra (dd/mm/aa):");
        getContentPane().add(PurchaseDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 200, 30));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WhiteSolidBackground.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ReadDataBase() {
        int i = 0;
        int rn = BusesTable.getRowCount();
        DefaultTableModel table = (DefaultTableModel) BusesTable.getModel();
        while (i < rn) {
            table.removeRow(0);
            i++;
        }
        try {
            Statement st;
            st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM bus;");
            while (rs.next()) {
                String Row[] = new String[]{rs.getString("IdBus"), rs.getString("Model"),
                    rs.getString("Enrollment"), rs.getString("PurchaseDate"), rs.getString("Driver"), rs.getString("PropertyOf")};
                table.addRow(Row);
            }
        } catch (SQLException ex) {
        }

    }
    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        this.dispose();
        MasterMenu.B = false;
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void ModifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyButtonActionPerformed
        int i = BusesTable.getSelectedRow();
        if (i == -1)
            JOptionPane.showMessageDialog(null, "No has seleccionado nada", "Error", JOptionPane.ERROR_MESSAGE);
        else {
            try {
                int id = Integer.parseInt(BusesTable.getValueAt(i, 0).toString());
                Statement st;
                st = con.createStatement();
                st.executeUpdate("UPDATE bus SET Model='" + ModelComboBox.getSelectedItem().toString().substring(0, 1) + "', Enrollment='"
                        + EnrollmentTextField.getText() + "', PurchaseDate='" + PurchaseDateTextField.getText() + "', PropertyOf='"
                        + PropertyComboBox.getSelectedItem().toString().substring(0, 1) + "', Driver='"
                        + DriverComboBox.getSelectedItem().toString().substring(0, 1) + "' WHERE IdBus=" + id);
                ReadDataBase();
                JOptionPane.showMessageDialog(null, "Se Actualizaron los datos del autobus", "Listo", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
            }
        }
    }//GEN-LAST:event_ModifyButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        int i = BusesTable.getSelectedRow();
        if (i == -1)
            JOptionPane.showMessageDialog(null, "No has seleccionado nada", "Error", JOptionPane.ERROR_MESSAGE);
        else {
            try {
                int id = Integer.parseInt(BusesTable.getValueAt(i, 0).toString());
                Statement st;
                st = con.createStatement();
                st.executeUpdate("DELETE FROM bus WHERE IdBus=" + id);
                DefaultTableModel table = (DefaultTableModel) BusesTable.getModel();
                table.removeRow(i);
                JOptionPane.showMessageDialog(null, "Se elimino el autobus de la lista", "Listo", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "El dato que quieres eliminar esta ligado a otro registro", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        try {
            boolean exists = false;
            String roll = EnrollmentTextField.getText();
            roll = roll.toLowerCase();

            Statement stE = con.createStatement();
            ResultSet rsE = stE.executeQuery("SELECT * FROM bus");

            while (rsE.next()) {
                String comp = rsE.getString("Enrollment");
                comp = comp.toLowerCase();
                if (comp.equalsIgnoreCase(roll)) {
                    exists = true;
                }
            }
            stE.close();

            if (exists == true) {
                JOptionPane.showMessageDialog(null, "Ya existe una matricula igual en el sistema!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {

                Statement st = con.createStatement();
                if ("".equals(EnrollmentTextField.getText()) || "".equals(PurchaseDateTextField.getText())) {
                    JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    st.execute("INSERT INTO `bus` (`IdBus`, `Model`, `Enrollment`, `PurchaseDate`, `PropertyOf`, `Driver`) "
                            + "VALUES (NULL,'" + ModelComboBox.getSelectedItem().toString().substring(0, 1) + "','"
                            + EnrollmentTextField.getText() + "','" + PurchaseDateTextField.getText() + "','"
                            + PropertyComboBox.getSelectedItem().toString().substring(0, 1) + "','" + DriverComboBox.getSelectedItem().toString().substring(0, 1) + "')");
                    JOptionPane.showMessageDialog(null, "El autobus se añadio a la lista", "Listo", JOptionPane.INFORMATION_MESSAGE);
                    ReadDataBase();
                }
            }
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageBuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageBuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageBuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageBuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageBuses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel Background;
    private javax.swing.JTable BusesTable;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JComboBox<String> DriverComboBox;
    private javax.swing.JLabel DriverLabel;
    private javax.swing.JLabel EnrollmentLabel;
    private javax.swing.JTextField EnrollmentTextField;
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel Logo;
    private javax.swing.JComboBox<String> ModelComboBox;
    private javax.swing.JLabel ModelLabel;
    private javax.swing.JButton ModifyButton;
    private javax.swing.JComboBox<String> PropertyComboBox;
    private javax.swing.JLabel PropertyLabel;
    private javax.swing.JLabel PurchaseDateLabel;
    private javax.swing.JTextField PurchaseDateTextField;
    private javax.swing.JLabel TittleLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
