package busstation;

import static busstation.LogIn.*;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ManageModels extends javax.swing.JFrame {

    public ManageModels() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        StartConnection();
        ReadDataBase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameTextField = new javax.swing.JTextField();
        BrandTextField = new javax.swing.JTextField();
        YearTextField = new javax.swing.JTextField();
        ExitButton = new javax.swing.JButton();
        ModifyButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        CapacitySpinner = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        ModelTable = new javax.swing.JTable();
        NameLabel = new javax.swing.JLabel();
        BrandLabel = new javax.swing.JLabel();
        CapacityLabel = new javax.swing.JLabel();
        YearLabel = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        TittleLabel = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("BusStation Pátzcuaro: Admin de modelos");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameTextField.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        NameTextField.setToolTipText("Escribe aquí el nombre del modelo.");
        NameTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 1, true));
        getContentPane().add(NameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 200, 30));

        BrandTextField.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        BrandTextField.setToolTipText("Escribe aquí la marca del modelo.");
        BrandTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 1, true));
        getContentPane().add(BrandTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 200, 30));

        YearTextField.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        YearTextField.setToolTipText("Escribe aquí el año del modelo.");
        YearTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 1, true));
        getContentPane().add(YearTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 200, 30));

        ExitButton.setBackground(new java.awt.Color(255, 153, 153));
        ExitButton.setText("CERRAR");
        ExitButton.setToolTipText("Click aquí para cerrar la ventana.");
        ExitButton.setBorder(null);
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 60, 20));

        ModifyButton.setBackground(new java.awt.Color(102, 153, 255));
        ModifyButton.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        ModifyButton.setText("MODIFICAR");
        ModifyButton.setToolTipText("Click aquí para modificar el modelo seleccionado.");
        ModifyButton.setBorder(null);
        ModifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ModifyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 170, 30));

        DeleteButton.setBackground(new java.awt.Color(255, 153, 153));
        DeleteButton.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        DeleteButton.setText("ELIMINAR");
        DeleteButton.setToolTipText("Click aquí para eliminar el modelo seleccionado.");
        DeleteButton.setBorder(null);
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 170, 30));

        AddButton.setBackground(new java.awt.Color(153, 255, 153));
        AddButton.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        AddButton.setText("AGREGAR");
        AddButton.setToolTipText("Click aquí para agregar un nuevo modelo con los datos proporcionados.");
        AddButton.setBorder(null);
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 170, 30));

        CapacitySpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        CapacitySpinner.setToolTipText("Selecciona aquí la capacidad del modelo.");
        getContentPane().add(CapacitySpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 200, 30));

        ModelTable.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        ModelTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Marca", "Capacidad", "Año"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ModelTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 660, 170));

        NameLabel.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        NameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameLabel.setText("Nombre:");
        getContentPane().add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 200, 30));

        BrandLabel.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        BrandLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BrandLabel.setText("Marca:");
        getContentPane().add(BrandLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 200, 30));

        CapacityLabel.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        CapacityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CapacityLabel.setText("Capacidad:");
        getContentPane().add(CapacityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 200, 30));

        YearLabel.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        YearLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        YearLabel.setText("Año:");
        getContentPane().add(YearLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 200, 30));

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo480.jpg"))); // NOI18N
        Logo.setToolTipText("");
        Logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 680, 40));

        TittleLabel.setFont(new java.awt.Font("HelvLight", 1, 14)); // NOI18N
        TittleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TittleLabel.setText("Registro y administracion de Modelos de autobuses");
        getContentPane().add(TittleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 680, 30));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WhiteSolidBackground.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ReadDataBase() {
        int i = 0;
        int rn = ModelTable.getRowCount();
        DefaultTableModel table = (DefaultTableModel) ModelTable.getModel();
        while (i < rn) {
            table.removeRow(0);
            i++;
        }
        try {
            Statement st;
            st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM model;");
            while (rs.next()) {
                String Row[] = new String[]{rs.getString("IdModel"), rs.getString("Name"),
                    rs.getString("Brand"), rs.getString("Capacity"), rs.getString("Year")};
                table.addRow(Row);
            }
        } catch (SQLException ex) {
        }
    }

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        this.dispose();
        MasterMenu.G = false;
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void ModifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyButtonActionPerformed
        int i = ModelTable.getSelectedRow();
        if (i == -1)
            JOptionPane.showMessageDialog(null, "No has seleccionado ningun Modelo de autobus", "Error", JOptionPane.ERROR_MESSAGE);
        else {
            try {
                int id = Integer.parseInt(ModelTable.getValueAt(i, 0).toString());
                Statement st;
                st = con.createStatement();
                st.executeUpdate("UPDATE model SET Name='" + NameTextField.getText() + "', Brand='"
                        + BrandTextField.getText() + "', Capacity=" + CapacitySpinner.getValue().toString() + ", Year="
                        + YearTextField.getText() + " WHERE IdModel=" + id);
                ReadDataBase();
                JOptionPane.showMessageDialog(null, "Se Actualizaron los datos del modelo", "Listo", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
            }
        }
    }//GEN-LAST:event_ModifyButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        int i = ModelTable.getSelectedRow();
        if (i == -1)
            JOptionPane.showMessageDialog(null, "No has seleccionado ningun Modelo de autobus", "Error", JOptionPane.ERROR_MESSAGE);
        else {
            try {
                int id = Integer.parseInt(ModelTable.getValueAt(i, 0).toString());
                Statement st;
                st = con.createStatement();
                st.executeUpdate("DELETE FROM model WHERE IdModel=" + id);
                DefaultTableModel table = (DefaultTableModel) ModelTable.getModel();
                table.removeRow(i);
                JOptionPane.showMessageDialog(null, "Se elimino el modelo de la lista", "Listo", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
            }
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        try {
            boolean exists = false;
            String comp = "";
            String model = NameTextField.getText() + " " + BrandTextField.getText();
            model = model.toLowerCase();

            Statement stM = con.createStatement();
            ResultSet rsM = stM.executeQuery("SELECT * FROM model");

            while (rsM.next()) {
                String A = rsM.getString("Name");
                String B = rsM.getString("Brand");
                comp = A + " " + B;
                comp = comp.toLowerCase();
                if (comp.equalsIgnoreCase(model)) {
                    exists = true;
                }
            }
            stM.close();

            if (exists == true) {
                JOptionPane.showMessageDialog(null, "Ya existe un conductor del mismo nombre\n"
                        + "dentro del sistema.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                Statement st = con.createStatement();
                if ("".equals(NameTextField.getText()) || "".equals(YearTextField.getText())
                        || "".equals(BrandTextField.getText())) {
                    JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    st.execute("INSERT INTO `model` (`IdModel`, `Name`, `Brand`, `Capacity`, `Year`) "
                            + "VALUES (NULL,'" + NameTextField.getText() + "','" + BrandTextField.getText() + "',"
                            + CapacitySpinner.getValue().toString() + "," + YearTextField.getText() + ")");
                    JOptionPane.showMessageDialog(null, "El modelo se ha añadido a la lista", "Listo", JOptionPane.INFORMATION_MESSAGE);
                    ReadDataBase();
                }
            }
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageModels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageModels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageModels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageModels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageModels().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel BrandLabel;
    private javax.swing.JTextField BrandTextField;
    private javax.swing.JLabel CapacityLabel;
    private javax.swing.JSpinner CapacitySpinner;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel Logo;
    private javax.swing.JTable ModelTable;
    private javax.swing.JButton ModifyButton;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JLabel TittleLabel;
    private javax.swing.JLabel YearLabel;
    private javax.swing.JTextField YearTextField;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
