package busstation;

import static busstation.LogIn.*;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ManageCompany extends javax.swing.JFrame {

    public ManageCompany() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        StartConnection();
        ReadDataBase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameTextField = new javax.swing.JTextField();
        LeaderTextField = new javax.swing.JTextField();
        PhoneNumberTextField = new javax.swing.JTextField();
        RegisterDateTextField = new javax.swing.JTextField();
        ExitButton = new javax.swing.JButton();
        ModifyButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CompanyTable = new javax.swing.JTable();
        NameLabel = new javax.swing.JLabel();
        NameLeaderLabel = new javax.swing.JLabel();
        PhoneLabel = new javax.swing.JLabel();
        RegisterDateLabel = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        TittleLabel = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("BusStation Pátzcuaro: Admin de lineas de autobuses");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameTextField.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        NameTextField.setToolTipText("Escribe aquí el nombre de la empresa.");
        NameTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 1, true));
        getContentPane().add(NameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 310, 30));

        LeaderTextField.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        LeaderTextField.setToolTipText("Escribe aquí el nombre del encargado la empresa.");
        LeaderTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 1, true));
        getContentPane().add(LeaderTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 310, 30));

        PhoneNumberTextField.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        PhoneNumberTextField.setToolTipText("Proporciona el numero de teléfono de la empresa.");
        PhoneNumberTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 1, true));
        getContentPane().add(PhoneNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 310, 30));

        RegisterDateTextField.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        RegisterDateTextField.setToolTipText("Escribe la fecha de registro con el formato que se indica.");
        RegisterDateTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 1, true));
        getContentPane().add(RegisterDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 310, 30));

        ExitButton.setBackground(new java.awt.Color(255, 153, 153));
        ExitButton.setText("CERRAR");
        ExitButton.setToolTipText("Click aquí para cerrar la ventana.");
        ExitButton.setBorder(null);
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 60, 20));

        ModifyButton.setBackground(new java.awt.Color(102, 153, 255));
        ModifyButton.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        ModifyButton.setText("MODIFICAR");
        ModifyButton.setToolTipText("Click aquí para modificar la linea seleccionada.");
        ModifyButton.setBorder(null);
        ModifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ModifyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 170, 30));

        DeleteButton.setBackground(new java.awt.Color(255, 153, 153));
        DeleteButton.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        DeleteButton.setText("ELIMINAR");
        DeleteButton.setToolTipText("Click aquí para eliminar la linea seleccionada.");
        DeleteButton.setBorder(null);
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 170, 30));

        AddButton.setBackground(new java.awt.Color(153, 255, 153));
        AddButton.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        AddButton.setText("AGREGAR");
        AddButton.setToolTipText("Click aquí para agregar una nueva linea con los datos proporcionados.");
        AddButton.setBorder(null);
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 170, 30));

        CompanyTable.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        CompanyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Encargado", "Telefono", "Fecha de registro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(CompanyTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 660, 170));

        NameLabel.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        NameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameLabel.setText("Nombre de la empresa:");
        getContentPane().add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 310, 30));

        NameLeaderLabel.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        NameLeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameLeaderLabel.setText("Nombre del encargado:");
        getContentPane().add(NameLeaderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 310, 30));

        PhoneLabel.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        PhoneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PhoneLabel.setText("Teléfono:");
        getContentPane().add(PhoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 310, 30));

        RegisterDateLabel.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        RegisterDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegisterDateLabel.setText("Fecha de Registro (aa-mm-dd):");
        getContentPane().add(RegisterDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 310, 30));

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo480.jpg"))); // NOI18N
        Logo.setToolTipText("");
        Logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 680, 40));

        TittleLabel.setFont(new java.awt.Font("HelvLight", 1, 14)); // NOI18N
        TittleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TittleLabel.setText("Registro y administracion de Lineas de Autobuses");
        getContentPane().add(TittleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 680, 30));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WhiteSolidBackground.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ReadDataBase() {
        int i = 0;
        int rn = CompanyTable.getRowCount();
        DefaultTableModel table = (DefaultTableModel) CompanyTable.getModel();
        while (i < rn) {
            table.removeRow(0);
            i++;
        }
        try {
            Statement st;
            st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM company;");
            while (rs.next()) {
                String Row[] = new String[]{rs.getString("IdCompany"), rs.getString("Name"),
                    rs.getString("Leader"), rs.getString("PhoneNumber"), rs.getString("RegistrationDate")};
                table.addRow(Row);
            }
        } catch (SQLException ex) {
        }
    }

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        this.dispose();
        MasterMenu.C = false;
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void ModifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyButtonActionPerformed
        int i = CompanyTable.getSelectedRow();
        if (i == -1)
            JOptionPane.showMessageDialog(null, "No has seleccionado ninguna linea de autobuses", "Error", JOptionPane.ERROR_MESSAGE);
        else {
            try {
                int id = Integer.parseInt(CompanyTable.getValueAt(i, 0).toString());
                Statement st;
                st = con.createStatement();
                st.executeUpdate("UPDATE company SET Name='" + NameTextField.getText() + "', Leader='"
                        + LeaderTextField.getText() + "', PhoneNumber='" + PhoneNumberTextField.getText() + "', RegistrationDate='"
                        + RegisterDateTextField.getText() + "' WHERE IdCompany=" + id);
                ReadDataBase();
                JOptionPane.showMessageDialog(null, "Se Actualizaron los datos de la compañia", "Listo", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Algunos de los datos no cumplen con el formato pedido", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_ModifyButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        int i = CompanyTable.getSelectedRow();
        if (i == -1)
            JOptionPane.showMessageDialog(null, "No has seleccionado nada", "Error", JOptionPane.ERROR_MESSAGE);
        else {
            try {
                int id = Integer.parseInt(CompanyTable.getValueAt(i, 0).toString());
                Statement st;
                st = con.createStatement();
                st.executeUpdate("DELETE FROM company WHERE IdCompany=" + id);
                DefaultTableModel table = (DefaultTableModel) CompanyTable.getModel();
                table.removeRow(i);
                JOptionPane.showMessageDialog(null, "Se elimino la compañia de la lista", "Listo", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
            }
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        try {

            boolean exists = false;
            String CO = NameTextField.getText();
            CO = CO.toLowerCase();

            Statement stC = con.createStatement();
            ResultSet rsC = stC.executeQuery("SELECT * FROM company");

            while (rsC.next()) {
                String comp = rsC.getString("Name");
                comp = comp.toLowerCase();
                if (comp.equalsIgnoreCase(CO)) {
                    exists = true;
                }
            }
            stC.close();

            if (exists == true) {
                JOptionPane.showMessageDialog(null, "Ya existe una empresa, curiosamente igual en el sistema.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                Statement st = con.createStatement();
                if ("".equals(NameTextField.getText()) || "".equals(NameTextField.getText())
                        || "".equals(LeaderTextField.getText())) {
                    JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    st.execute("INSERT INTO `company` (`IdCompany`, `Name`, `Leader`, `PhoneNumber`, `RegistrationDate`) "
                            + "VALUES (NULL,'" + NameTextField.getText() + "','" + LeaderTextField.getText() + "','"
                            + PhoneNumberTextField.getText() + "','" + RegisterDateTextField.getText() + "')");
                    JOptionPane.showMessageDialog(null, "Se ha añadido la compañia a la lista.", "Listo", JOptionPane.INFORMATION_MESSAGE);
                    ReadDataBase();
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Algunos de los datos no cumplen con el formato pedido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageCompany().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel Background;
    private javax.swing.JTable CompanyTable;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField LeaderTextField;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton ModifyButton;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel NameLeaderLabel;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JLabel PhoneLabel;
    private javax.swing.JTextField PhoneNumberTextField;
    private javax.swing.JLabel RegisterDateLabel;
    private javax.swing.JTextField RegisterDateTextField;
    private javax.swing.JLabel TittleLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
