package busstation;

import static busstation.LogIn.*;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ManageDrivers extends javax.swing.JFrame {

    public ManageDrivers() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        StartConnection();
        ReadDataBase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameTextField = new javax.swing.JTextField();
        AddressTextField = new javax.swing.JTextField();
        LastNameTextField = new javax.swing.JTextField();
        SalaryTextField = new javax.swing.JTextField();
        PhoneNumberTextField = new javax.swing.JTextField();
        BirthDateTextField = new javax.swing.JTextField();
        ExitButton = new javax.swing.JButton();
        ModifyButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DriversTable = new javax.swing.JTable();
        NameLabel = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        AddressLabel = new javax.swing.JLabel();
        SalaryLabel = new javax.swing.JLabel();
        PhoneLabel = new javax.swing.JLabel();
        BirthDateLabel = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        TittleLabel = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("BusStation Pátzcuaro: Admin de conductores");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameTextField.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        NameTextField.setToolTipText("Escribe aquí el nombre de pila del conductor.");
        NameTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 1, true));
        getContentPane().add(NameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 200, 30));

        AddressTextField.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        AddressTextField.setToolTipText("Proporciona una dirección o ubicación del conductor.");
        AddressTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 1, true));
        getContentPane().add(AddressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 200, 30));

        LastNameTextField.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        LastNameTextField.setToolTipText("Escribe aquí el o los apellidos del conductor.");
        LastNameTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 1, true));
        getContentPane().add(LastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 200, 30));

        SalaryTextField.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        SalaryTextField.setToolTipText("Proporciona un sueldo para el conductor.");
        SalaryTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 1, true));
        getContentPane().add(SalaryTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 200, 30));

        PhoneNumberTextField.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        PhoneNumberTextField.setToolTipText("Proporciona un número de teléfono del conductor.");
        PhoneNumberTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 1, true));
        getContentPane().add(PhoneNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 200, 30));

        BirthDateTextField.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        BirthDateTextField.setToolTipText("Escribe la fecha de nacimiento con el formato que se indica.");
        BirthDateTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 1, true));
        getContentPane().add(BirthDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 200, 30));

        ExitButton.setBackground(new java.awt.Color(255, 153, 153));
        ExitButton.setText("CERRAR");
        ExitButton.setToolTipText("Click aquí para cerrar la ventana.");
        ExitButton.setBorder(null);
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 60, 20));

        ModifyButton.setBackground(new java.awt.Color(102, 153, 255));
        ModifyButton.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        ModifyButton.setText("MODIFICAR");
        ModifyButton.setToolTipText("Click aquí para modificar el conductor seleccionado.");
        ModifyButton.setBorder(null);
        ModifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ModifyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 170, 30));

        DeleteButton.setBackground(new java.awt.Color(255, 153, 153));
        DeleteButton.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        DeleteButton.setText("ELIMINAR");
        DeleteButton.setToolTipText("Click aquí para eliminar el conductor seleccionado.");
        DeleteButton.setBorder(null);
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 170, 30));

        AddButton.setBackground(new java.awt.Color(153, 255, 153));
        AddButton.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        AddButton.setText("AGREGAR");
        AddButton.setToolTipText("Click aquí para agregar un nuevo conductor con los datos proporcionados.");
        AddButton.setBorder(null);
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 170, 30));

        DriversTable.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        DriversTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Direccion", "Telefono", "Fecha Nacimiento", "Sueldo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(DriversTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 660, 170));

        NameLabel.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        NameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameLabel.setText("Nombre:");
        getContentPane().add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 200, 30));

        LastNameLabel.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        LastNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LastNameLabel.setText("Apellidos:");
        getContentPane().add(LastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 200, 30));

        AddressLabel.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        AddressLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddressLabel.setText("Dirección:");
        getContentPane().add(AddressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 200, 30));

        SalaryLabel.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        SalaryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SalaryLabel.setText("Sueldo:");
        getContentPane().add(SalaryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 200, 30));

        PhoneLabel.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        PhoneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PhoneLabel.setText("Teléfono:");
        getContentPane().add(PhoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 200, 30));

        BirthDateLabel.setFont(new java.awt.Font("HelvLight", 0, 12)); // NOI18N
        BirthDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BirthDateLabel.setText("Fecha de Nacimiento (aa/mm/dd):");
        getContentPane().add(BirthDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 200, 30));

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo480.jpg"))); // NOI18N
        Logo.setToolTipText("");
        Logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 680, 40));

        TittleLabel.setFont(new java.awt.Font("HelvLight", 1, 14)); // NOI18N
        TittleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TittleLabel.setText("Registro y administracion de Conductores");
        getContentPane().add(TittleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 680, 30));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WhiteSolidBackground.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ReadDataBase() {
        int i = 0;
        int rn = DriversTable.getRowCount();
        DefaultTableModel table = (DefaultTableModel) DriversTable.getModel();
        while (i < rn) {
            table.removeRow(0);
            i++;
        }
        try {
            Statement st;
            st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM driver;");
            while (rs.next()) {
                String Row[] = new String[]{rs.getString("IdDriver"), rs.getString("Name") + " " + rs.getString("LastName"),
                    rs.getString("Address"), rs.getString("PhoneNumber"), rs.getString("BirthDate"), rs.getString("Salary")};
                table.addRow(Row);
            }
        } catch (SQLException ex) {
        }
    }

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        this.dispose();
        MasterMenu.D = false;
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void ModifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyButtonActionPerformed
        int i = DriversTable.getSelectedRow();
        if (i == -1)
            JOptionPane.showMessageDialog(null, "No has seleccionado nada", "Error", JOptionPane.ERROR_MESSAGE);
        else {
            try {
                int id = Integer.parseInt(DriversTable.getValueAt(i, 0).toString());
                Statement st;
                st = con.createStatement();
                st.executeUpdate("UPDATE driver SET Name='" + NameTextField.getText() + "', LastName='"
                        + LastNameTextField.getText() + "', Address='" + AddressTextField.getText() + "', PhoneNumber="
                        + PhoneNumberTextField.getText() + ", BirthDate='" + BirthDateTextField.getText()
                        + "', Salary=" + SalaryTextField.getText() + " WHERE IdDriver=" + id);
                ReadDataBase();
                JOptionPane.showMessageDialog(null, "Se Actualizaron los datos del conductor", "Listo", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
            }
        }
    }//GEN-LAST:event_ModifyButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        int i = DriversTable.getSelectedRow();
        if (i == -1)
            JOptionPane.showMessageDialog(null, "No has seleccionado ningun conductor", "Error", JOptionPane.ERROR_MESSAGE);
        else {
            try {
                int id = Integer.parseInt(DriversTable.getValueAt(i, 0).toString());
                Statement st;
                st = con.createStatement();
                st.executeUpdate("DELETE FROM driver WHERE IdDriver=" + id);
                DefaultTableModel table = (DefaultTableModel) DriversTable.getModel();
                table.removeRow(i);
                JOptionPane.showMessageDialog(null, "Se elimino el conductor de la lista", "Listo", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
            }
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        try {
            boolean exists = false;
            String comp = "";
            String driver = NameTextField.getText() + " " + LastNameTextField.getText();
            driver = driver.toLowerCase();

            Statement stR = con.createStatement();
            ResultSet rsR = stR.executeQuery("SELECT * FROM driver");

            while (rsR.next()) {
                String A = rsR.getString("Name");
                String B = rsR.getString("LastName");
                comp = A + " " + B;
                comp = comp.toLowerCase();
                if (comp.equalsIgnoreCase(driver)) {
                    exists = true;
                }
            }
            stR.close();

            if (exists == true) {
                JOptionPane.showMessageDialog(null, "Ya existe un conductor del mismo nombre\n"
                        + "dentro del sistema.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                Statement st = con.createStatement();
                if ("".equals(NameTextField.getText()) || "".equals(NameTextField.getText())
                        || "".equals(AddressTextField.getText())) {
                    JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    st.execute("INSERT INTO `driver` (`IdDriver`, `Name`, `LastName`, `Address`, `PhoneNumber`, `BirthDate`, `Salary`)"
                            + "VALUES (NULL,'" + NameTextField.getText() + "','" + LastNameTextField.getText() + "','"
                            + AddressTextField.getText() + "'," + PhoneNumberTextField.getText() + ",'"
                            + BirthDateTextField.getText() + "'," + SalaryTextField.getText() + ")");
                    JOptionPane.showMessageDialog(null, "El conductor se ha añadido a la lista   ", "Listo", JOptionPane.INFORMATION_MESSAGE);
                    ReadDataBase();
                }
            }
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageDrivers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageDrivers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageDrivers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageDrivers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageDrivers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JTextField AddressTextField;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel BirthDateLabel;
    private javax.swing.JTextField BirthDateTextField;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JTable DriversTable;
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton ModifyButton;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JLabel PhoneLabel;
    private javax.swing.JTextField PhoneNumberTextField;
    private javax.swing.JLabel SalaryLabel;
    private javax.swing.JTextField SalaryTextField;
    private javax.swing.JLabel TittleLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
