package busstation;

public class Tickets extends javax.swing.JFrame {
    
    static int id, seat;
    static String destiny, hour, date;
    
    public Tickets() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setTitle("Ticket N° "+id);
        SeatLabel1.setText("#"+seat);
        SeatLabel2.setText("#"+seat);
        hour = hour.substring(0,5);
        HourLabel1.setText(hour);
        HourLabel2.setText(hour);
        DateLabel1.setText(date);
        DateLabel2.setText(date);
        destiny = destiny.substring(0,3).toUpperCase();
        DestLabel3.setText(destiny);
        DestLabel4.setText(destiny);
    }
    
    public static void SetValues (int ID, int SEAT, String DESTINY, String HOUR, String DATE){
        id = ID;
        seat = SEAT;
        destiny = DESTINY;
        hour = HOUR;
        date = DATE;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HourLabel1 = new javax.swing.JLabel();
        HourLabel2 = new javax.swing.JLabel();
        SeatLabel1 = new javax.swing.JLabel();
        SeatLabel2 = new javax.swing.JLabel();
        DestLabel1 = new javax.swing.JLabel();
        DestLabel2 = new javax.swing.JLabel();
        DestLabel3 = new javax.swing.JLabel();
        DestLabel4 = new javax.swing.JLabel();
        DateLabel1 = new javax.swing.JLabel();
        DateLabel2 = new javax.swing.JLabel();
        TicketLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ticket ###");
        setMaximumSize(new java.awt.Dimension(496, 526));
        setMinimumSize(new java.awt.Dimension(496, 526));
        setPreferredSize(new java.awt.Dimension(496, 526));
        setResizable(false);
        setSize(new java.awt.Dimension(496, 526));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HourLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        HourLabel1.setForeground(new java.awt.Color(201, 99, 32));
        HourLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HourLabel1.setText("00:00");
        getContentPane().add(HourLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 110, 30));

        HourLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        HourLabel2.setForeground(new java.awt.Color(201, 99, 32));
        HourLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HourLabel2.setText("00:00");
        getContentPane().add(HourLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 110, 30));

        SeatLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        SeatLabel1.setForeground(new java.awt.Color(255, 204, 153));
        SeatLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SeatLabel1.setText("###");
        getContentPane().add(SeatLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 70, 30));

        SeatLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        SeatLabel2.setForeground(new java.awt.Color(255, 204, 153));
        SeatLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SeatLabel2.setText("###");
        getContentPane().add(SeatLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 80, 30));

        DestLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DestLabel1.setForeground(new java.awt.Color(201, 99, 32));
        DestLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DestLabel1.setText("PTZ >");
        getContentPane().add(DestLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 60, 30));

        DestLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        DestLabel2.setForeground(new java.awt.Color(201, 99, 32));
        DestLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DestLabel2.setText("PTZ >");
        getContentPane().add(DestLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 60, 30));

        DestLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        DestLabel3.setForeground(new java.awt.Color(201, 99, 32));
        DestLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DestLabel3.setText("ABC");
        getContentPane().add(DestLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 70, 30));

        DestLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DestLabel4.setForeground(new java.awt.Color(201, 99, 32));
        DestLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DestLabel4.setText("ABC");
        getContentPane().add(DestLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 80, 30));

        DateLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DateLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DateLabel1.setText("DD-MM-AAAA");
        getContentPane().add(DateLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 130, 30));

        DateLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DateLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DateLabel2.setText("DD-MM-AAAA");
        getContentPane().add(DateLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 100, 30));

        TicketLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TicketR.jpg"))); // NOI18N
        getContentPane().add(TicketLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 500, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tickets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DateLabel1;
    private javax.swing.JLabel DateLabel2;
    private javax.swing.JLabel DestLabel1;
    private javax.swing.JLabel DestLabel2;
    private javax.swing.JLabel DestLabel3;
    private javax.swing.JLabel DestLabel4;
    private javax.swing.JLabel HourLabel1;
    private javax.swing.JLabel HourLabel2;
    private javax.swing.JLabel SeatLabel1;
    private javax.swing.JLabel SeatLabel2;
    private javax.swing.JLabel TicketLabel;
    // End of variables declaration//GEN-END:variables
}
